# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5e05e62c-ff65-4b73-aed4-ece47c9d8692";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4E0C-E472";
      fsType = "vfat";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/bff8fe44-6ada-4395-b9c7-b2aaf46f0fb9"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
